### ISSUE TITLE
Locale issues when using Enum name()

### ISSUE THREAD

**Issue by Linguardium** [lanAnderson/SeasonInfo#48]
https://github.com/lanAnderson/SeasonHUD/blob/d4ec53f41d118d8b7857c0857a6f88a0f2c0562f/fabric/src/main/java/club/iananderson/seasonhud/impl/fabricseasons/CurrentSeason.java#L28C10-L28C10

This uses system locale, which may not be english, which may create an identifier with invalid characters in https://github.com/lanAnderson/SeasonHUD/blob/d4ec53f41d118d8b7857c0857a6f88a0f2c0562f/fabric/src/main/java/club/iananderson/seasonhud/impl/fabricseasons/CurrentSeason.java#L62-L65

It may be prudent to use a specific locale with the toLowerCase, and also probably use the asString method of the enum since it implements StringIdentifiable

**Comment by lanAnderson** [comment]
Corrected in version 1.5.12

**Comment by Linguardium** [comment]
still not corrected. 

toLowerCase is locale sensitive, you are not providing a locale so it is trying to use the host computer's locale for it. Since the host computer may be german, turkish, etc, the string converts the letters to the locale dependent lowercase (latin i, etc) breaking the resource path.

I would recommend supplying it with Locale.ROOT in cases where locale matters
