### ISSUE TITLE
Pressing F1 Does Not Hide The Text

### ISSUE THREAD

**Issue by UnknownSerhan** [lanAnderson/SeasonInfo#95]
**Describe the issue**

- When we press F1, the text isn't hid from the screen.

**Minecraft Version**

- 1.21.

**Mod Version**

- 1.8.8.

**Modloader(Fabric/Forge/NeoForge)**

- NeoForge.

**Modloader Version**

- 21.0.40-beta.

**Additional Info (Crashlog/Modlist)**

- Journeymap is installed.

**Comment by lanAnderson** [comment]
Odd, it used to just hide all guis automatically but that seems to have changed in 1.20.6. I'll add a check and include it in previous versions just in case.

**Comment by lanAnderson** [comment]
Fixed in 1.8.9

**Comment by UnknownSerhan** [comment]
The issue still occurs in 1.9.7 (journeymap is still installed)
![2024-07-28_16 41 55](https://github.com/user-attachments/assets/c85c6e7a-3c92-4b75-97b5-db01c87ffbe7)
